```{r}
library(readxl)
library(dplyr)
library(lubridate)

weather <- read.csv("data/weather_final.csv")
weather$Date <- as.Date(weather$date)
weather <- weather %>% arrange(Date)

racedate <- read_excel("data/racedate.xlsx")
race_summary <- read.csv("data/race_summary.csv")

racedate <- subset(racedate, Season >= 1992)
racedate <- racedate %>%
  mutate(Date = make_date(Season, month(Date), day(Date)))
racedate <- racedate %>% arrange(Date)

merged_df <- cbind(racedate, race_summary)

final_merged_df <- merged_df %>%
  right_join(weather, by = "Date")

final_merged_df <- final_merged_df %>%
  select(track_length, temp, dwpt, rhum,
         prcp, wspd, coco, rain_binary, shortened)

final_merged_df$rain_binary <- ifelse(final_merged_df$rain == "True", 1, 0)
final_merged_df$shortened <- ifelse(final_merged_df$shortened == "True", 1, 0)
final_merged_df$coco <- recode(final_merged_df$coco,
                               "No Rain" = 0,
                               "Light Rain" = 1,
                               "Moderate Rain" = 2,
                               "Heavy Rain" = 3,
                               .default = NA_real_)
head(final_merged_df)
```


```{r}
library(rjags)
library(R2jags)
library(dplyr)

y <- as.vector(final_merged_df$shortened)
X <- as.matrix(final_merged_df %>% select(temp, prcp, wspd))
N <- length(y)
K <- ncol(X)

modelString <- "
model {
  # Likelihood
  for (i in 1:N) {
    logit(p[i]) <- b0 + bTemp * temp[i] + bPrcp * prcp[i] + bWspd * wspd[i]
    y[i] ~ dbern(p[i])
  }
  p0 ~ dbeta(1, 1)
  b0 <- logit(p0)
  bPrcp ~ dunif(-10, 10)
  bTemp ~ dunif(-10, 10)
  bWspd ~ dunif(-10, 10)
}
"

the_data <- list(N = N, y = y,
    temp = final_merged_df$temp, prcp = final_merged_df$prcp, wspd = final_merged_df$wspd)

params <- c("bTemp", "bPrcp", "bWspd", "p0")

library(jagsUI)
posterior <- jags(the_data, NULL, parameters.to.save = params, 
                  model.file = textConnection(modelString),
                  n.chains=3, n.iter=10000,  n.burnin = 5000, n.thin = 2)


```